### ISSUE TITLE
Can be rancher installed on nodes in public subnet?

### ISSUE THREAD

**Issue by risayew** [techcto/datacenter#5]

**Comment by techcto** [comment]
Long time no see.  Were you waitng on me?  How is it going?

**Comment by risayew** [comment]
Oh, thank you! It was going quiet well with rancher 2.0 and cloud formation(i have even managed to add persistence storage via rancher UI by enabling aws cloud provider somewhere in config. although rancher cluster was running on public subnet-that was my issue here), until we decided to use Fargate for setup of our application. It was actually better decision, because hosting Rancher on 3xEC2 instances was rather expensive + Application itself needs additional Kubernetes cluster. So i removed rancher 2.0 from aws for the moment. But for next project i have plans to setup rancher 2.0 on Exoscale using terraform.

**Comment by risayew** [comment]
To be honest, i can't find good place for rancher if we are talking about "customer" applications. We are using rancher 1.6 on our private hosting for our infrastructure applications like gitlab, registries, pm-tool etc. But for customer applications everytime more thrifty variant will be chosen at the end. May be a kind of portability argument can play here for pro rancher decisions. But who wants portable backend? )

**Comment by techcto** [comment]
Funny you say that I also switched to AWS ECS and refactored our app into a Task Definition as well.  I made the best I could from what I was trying from Rancher to ECS.  I got it somewhat there; I still need to build a Proxy and a Service Registry so that I can use have multiple apps on a single ECS cluster.

I wished I could use Fargate, but I have not figured out persistent storage using something like EFS.  Does your app require access to persistent file storage?  If so, how do you handle that?

I have this project open-sourced as well, but unfortunately, it is app specific.  Would need a bit of updating to make it general purpose if you are ever interested: https://github.com/techcto/solodev-aws/blob/master/aws/solodev-enterprise-ecs.dev.yaml

In regards to cost, once this gets sorted, I am pretty certain the cost should be good, but the big gain we are going for is speed to deploy and scale.

Finally, most like I will go to Kubernetes with AWS before returning back to Rancher.  Please keep me posted as you make updates to your stack.  I am trying to make all my infrastructure work public, so always open to ideas.

**Comment by risayew** [comment]
Thank you for rancher templates! I have learned many new things for me.
Actually as i know, at the moment there is no possibility to use persistent storage with Fargate. In our application we could omit the persistence layer: we use just bucket and RDS. All other configuration is done via env. variables, i.e. via params. 
Interesting, I will take a look on your project. Of course i will tell you my ideas, if any good comes to my mind.
